### ISSUE TITLE
Configuration guide link goes to 404 error / does not exist

### ISSUE THREAD

**Issue by astupidmoose** [paxful/pwp-plugins#2]
https://github.com/paxful/pwp-plugins/blob/b6daf2313491893fb84cd0577eb3a31766d3a5be/templates/admin/admin-options.php#L27

Referenced document does not exist: https://paxful.com/pwp-plugin-manual/woocommerce.pdf
Gives 404 error.

**Comment by ozerk** [comment]
@astupidmoose the help documentation is updated in the new plugin release. 
you can see the installation guide from https://paxful.com/support/en-us/articles/360020524999-Paxful-Pay-WooCommerce-Plugin-Guide
